### ISSUE TITLE
Error copying gitignore file 

### ISSUE THREAD

**Issue by stvnrs** [stvnrs/generator-armed#6]
On running the generator it fails due to the template for the gitignore file not being found

Steps to recreate:
1. Install the generator 

```
npm install generator-armed 
```

2. create a folder for your solution and navigate to it:

```
md generator-fails-due-to-gitignore
cd generator-fails-due-to-gitignore
```

3. run  the generator:

```
yo armed
```

Output from generator:

```
? Your project name generator-fails-due-to-gitignore
? Add common deployment No
? Add tenant deployment No
? Add subscription deployment No
? Add group deployment Yes
? Name of group deployment core
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\generator-armed\generators\app\templates\git\.gitignore
    at EditionInterface.exports.copy (C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\yo\node_modules\mem-fs-editor\lib\actions\copy.js:49:3)
    at module.exports.writing (C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\generator-armed\generators\app\index.js:68:17)
    at Object.<anonymous> (C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\generator-armed\node_modules\yeoman-generator\lib\index.js:893:25)
    at C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\generator-armed\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\generator-armed\node_modules\run-async\index.js:26:19
    at runLoop.add.once.once (C:\Users\StevenRose_oisq8sf\AppData\Roaming\npm\node_modules\generator-armed\node_modules\yeoman-generator\lib\index.js:894:11)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

```

**Comment by stvnrs** [comment]
Issue appears to be the gitgnore file being excluded when the generator is packaged for deployment to the npm repository
